import { MedusaService } from "@medusajs/framework/utils"
import { Publisher } from "./models/publisher"
import { Writer } from "./models/writer"

/** CRUD for writers and publishers (generated by MedusaService) */
class BrandsModuleService extends MedusaService({ Writer, Publisher }) {}

export default BrandsModuleService
