/**
 * Writes `.env.live.local` with the publishable key and region id of the seeded Medusa database.
 * The seed (backend/apps/backend/src/migration-scripts/bookworm-seed.ts) creates a new key on every
 * fresh database, so these values can't be committed. Vite loads `.env.live.local` after `.env.live`.
 *
 * Usage: npm run live:env   (DATABASE_URL defaults to the docker-compose PostgreSQL)
 */

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

// pg is a backend dependency; the storefront doesn't need its own copy
const require = createRequire(new URL('../backend/package.json', import.meta.url));
const { Client } = require('pg');

const databaseUrl = process.env.DATABASE_URL ?? 'postgres://medusa:medusa@localhost:5433/bookworm';
const client = new Client({ connectionString: databaseUrl });

await client.connect();
try {
  const key = await client.query(
    `select token from api_key
      where type = 'publishable' and title = 'Book Worm storefront' and revoked_at is null and deleted_at is null
      order by created_at desc limit 1`
  );
  const region = await client.query(
    `select id from region where name = 'India' and deleted_at is null order by created_at desc limit 1`
  );
  if (key.rowCount === 0 || region.rowCount === 0) {
    console.error(
      'No seeded publishable key or India region found. Run `npm run backend:migrate` first.'
    );
    process.exit(1);
  }

  const target = new URL('../.env.live.local', import.meta.url);
  writeFileSync(
    target,
    [
      '# Generated by `npm run live:env` from the seeded database. Do not commit.',
      `VITE_MEDUSA_PUBLISHABLE_KEY=${key.rows[0].token}`,
      `VITE_MEDUSA_REGION_ID=${region.rows[0].id}`,
      '',
    ].join('\n')
  );
  console.log(`Wrote ${target.pathname} (region ${region.rows[0].id})`);
} finally {
  await client.end();
}
